name: ESLint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v1

      - name: Install dependencies
        run: |
          yarn install

      - name: Run ESLint
        run: |
          yarn lint --no-fix
